exp_name: 'efficientnetv2_rw_m_ArcFace_300_m04_s12_base'
outdir: './experiments/'

num_gpu: 1

dataset:
    root: 'path/to/dataset/images'
    train_list: 'path/to/dataset/train.csv'
    val_list: 'path/to/dataset/val.csv'
    val_path: 'path/to/val/images'
    cropped: true
    seed: 42
    num_of_classes: 102
    num_of_images: 28597
    input_size: 300
    padding: 0
    batch_size: 50
    augmentations: 'letterbox'
    augmentations_valid: 'letterbox'
    num_workers: 12


model:
    arch: 'efficientnetv2_rw_m'
    dropout: 0.02
    s: 12
    m: 0.4

train:
    fp16: true
    optimizer: 'AdamW'
    learning_rate: 0.000343
    momentum: 0.9
    weight_decay: 0.0018235327346030703
    lr_schedule:
        name: 'StepLR'
        step_size: 1
        gamma: 0.1
        max_steps: 10
        warmup_epoch: 2
    n_epoch: 5
    arcface:
        s: 12
        m: 0.4
    label_smoothing: 0.1
    eps: 0.01
    freq_vis: 500
